"""Add security and kyc attributes

Revision ID: afbadbdf96c0
Revises: b0193ab0c115
Create Date: 2026-04-23 01:44:14.824884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afbadbdf96c0'
down_revision: Union[str, Sequence[str], None] = 'b0193ab0c115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.String(), nullable=False))
    op.add_column('users', sa.Column('failed_pin_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('kyc_tier', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kyc_tier')
    op.drop_column('users', 'failed_pin_attempts')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
