"""Add Tontine and Enterprise models

Revision ID: c6b5c263b454
Revises: aac17db9eeab
Create Date: 2026-07-12 04:11:52.958985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlalchemy_utils.types.encrypted.encrypted_type


# revision identifiers, used by Alembic.
revision: str = 'c6b5c263b454'
down_revision: Union[str, Sequence[str], None] = 'aac17db9eeab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_id'), 'revoked_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_token'), 'revoked_tokens', ['token'], unique=True)
    op.create_table('tontine_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('contribution_amount', sa.Float(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_cycle', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tontine_groups_creator_id'), 'tontine_groups', ['creator_id'], unique=False)
    op.create_table('tontine_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tontine_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('payout_order', sa.Integer(), nullable=False),
    sa.Column('total_contributed', sa.Float(), nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tontine_id'], ['tontine_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tontine_members_id'), 'tontine_members', ['id'], unique=False)
    op.add_column('transactions', sa.Column('status', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('transaction_type', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('external_reference', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('description', sa.String(), nullable=True))
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    op.add_column('users', sa.Column('kyc_doc_path', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True))
    op.add_column('users', sa.Column('kyc_status', sa.String(), nullable=False))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('agent_score', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('agent_ratings_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'agent_ratings_count')
    op.drop_column('users', 'agent_score')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'kyc_status')
    op.drop_column('users', 'kyc_doc_path')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_column('transactions', 'description')
    op.drop_column('transactions', 'external_reference')
    op.drop_column('transactions', 'idempotency_key')
    op.drop_column('transactions', 'transaction_type')
    op.drop_column('transactions', 'status')
    op.drop_index(op.f('ix_tontine_members_id'), table_name='tontine_members')
    op.drop_table('tontine_members')
    op.drop_index(op.f('ix_tontine_groups_creator_id'), table_name='tontine_groups')
    op.drop_table('tontine_groups')
    op.drop_index(op.f('ix_revoked_tokens_token'), table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_id'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
